### ISSUE TITLE
Crash when [Remove Rigidbody Bone]

### ISSUE THREAD

**Issue by Irmitya** [dskjal/Rigidbody-Bone#1]
When playing animation _(begin physics simulation)_, if you stop away from the first frame and run [Remove Rigidbody Bone], Blender will crash.

Video example:  https://streamable.com/l1ybe
.blend file example:  [_rigidbody_crash_file.zip](https://github.com/dskjal/Rigidbody-Bone/files/3299170/_rigidbody_crash_file.zip)

The crash occurs at line # 327: `bpy.ops.rigidbody.world_remove()`

This is a bug with the Blender operator, however if you clear the cache before the operator runs `bpy.ops.dskjal.freerigidbodycache()`, Blender will not crash.

**Comment by Irmitya** [comment]
Is there any technical reason to "need" to delete the Rigidbody World?
Doing so removes other objects from the simulation, and creating another simulation would require "manually" adding objects into the next simulation.

**Comment by dskjal** [comment]
Can not reproduce the bug. Use latest blender and latest script.

The reason to delete the Rigidbody World is that it is the easiest way to delete the Rigidbody cache. Old Rigidbody cache sometimes hinders simulation.

If you don't mind that, you can remove the clause.

**Comment by Irmitya** [comment]
I was using the latest versions. 
I had yesterday's build and only switched back to the 9th's build later, because there's this material dependency loop error happening currently, that's causing a frequent delay. 

Windows 7 64bit

**Comment by dskjal** [comment]
Could you show me the material dependency loop error? I can't find any information about that.

**Comment by Irmitya** [comment]
The loop is irrelevant to what I'm reporting to you, it's just background information _(like the last time I shutdown my computer)_.

To answer your curiosity, the loop apparently happens when an object has nodes with a material referencing itself. 
![image](https://user-images.githubusercontent.com/10817631/59778182-a3e77b00-927b-11e9-8bf4-7fb17067d3f4.png)

This is from 2.7x's Blender Internal, when using a Material Input node. 
I used these to have the material display in GLSL mode, as how they would appear"without" using nodes, so that Cycles and Internal can be viewed interchangeably without having to toggle the use_nodes property on every material for each engine.

These nodes appear in the node_trees in 2.8 as Undefined with red boxes, so they're hard to miss. 
![image](https://user-images.githubusercontent.com/10817631/59778268-cd080b80-927b-11e9-8026-ed776c52254a.png)
And before you ask: 
Again, no, this has absolutely nothing to do with the issue. My file is newly created in 2.8 with no materials.

**Comment by dskjal** [comment]
Addon updated. Stopped to delete rigidbody world. I forgot that deleting the rigidbody world removes other object's rigidbody settings.

**Comment by Irmitya** [comment]
Unrelated: Since I learned what was causing that loop lag and having the nodes isn't important _(because I can't and don't want to go back)_, I can re-update. 

------------
But funny thing is that update removes the operator that could be used to prevent my crashes here. 

So, what's happening is when you explicitly remove the objects or mesh data from bpy.data (erasing them), Blender can no longer update with a frame change; pauses then crashes instead. 

The fix is to clear users and unlink object instead:
```
        for o in c.objects:
            # c.objects.unlink(o)  # Not needed since it can be removed with the other collections
            for col in o.users_collection:
                col.object.unlink(o)
            o.user_clear()
            if o.data:
                o.data.user_clear()
```
This will delete the objects and mark the meshes for removal. 

The only difference *(aside from it not crashing)* is the data is left in memory as orphans, instead of completely erased, freeing their names for further creation in the active file. 
Though, a circumvention for the names is to simply rename them before removal ¯\\\_(ツ)\_/¯

_edit: objects also need to be removed from other collections as well (particularly the rigidbody collection, so they don't stick around, interfering with simulation)_

**Comment by dskjal** [comment]
bpy.data.objects.remove(o) causes crash since the rigidbody of the object refer other object. I fixed that.

**Comment by Irmitya** [comment]
Works now, no crash. 
Thanks.
