### ISSUE TITLE
Current Experimental Builds Abort Creation: Context Changed

### ISSUE THREAD

**Issue by theoldben** [dskjal/Rigidbody-Bone#2]
When running RigidBodyBone in 2.81.8, I get the following error, which halts the creation of the RigidBodyBones. 

```
Traceback (most recent call last):
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\rigidbody-bone-280.py", line 258, in execute
    o = setup_box(amt, active, tree, i-1, o, collection)
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\rigidbody-bone-280.py", line 128, in setup_box
    bpy.ops.rigidbody.constraint_add()
  File "E:\Git-6fc6f2504dfd-05-Sep-02-56\2.81\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.rigidbody.constraint_add.poll() failed, context is incorrect

location: <unknown location>:-1
```

I can provide a sample file. But it only contains 3 bones in a chain.

**Comment by theoldben** [comment]
I have found the source of the failure: the add-on code is completely fine, it seems like **the experimental builds no longer support adding a RigidBody Constraint to Empties.**  

![image](https://user-images.githubusercontent.com/28691830/64420532-c1b8c500-d09f-11e9-8ae6-a979d07ba98d.png)

**Comment by dskjal** [comment]
It seems like Blender's bug. I have reported that. https://developer.blender.org/T69583

**Comment by theoldben** [comment]
Thank you! The master build still works, so in case anybody having this problem reads this: 
use the stable release.
